export const defaultTemplateStrings = [
	"appending an A* then *a B* gives *a C*",
	"*an A* is the reverse of a B*",
	"*a T1* is the same date as *a T2*",
	"*a Middle* is between a Minimum* & *a Maximum*",
	"*an A* is 1 day after a B*",
	"*an A* is a B* days after a C*",
	"*a T1* is immediately before *a T2*",
	"*a T1* is different from *a T2* *a T1* is equivalent to *a T2*",
	"*an Object is of type *a Type*",
	"*a T1* is not before *a T2*",
	"*a T1* is equal to *a T2*",
	"*a T1 is before a T2*",
	"*a T1* is after a T2*",
	"*a Member* is in *a List*",
	"*a A* is *a B*",  // TODO: this is going to be a problem...
	"*a T1* \\=@= *a T2*",
	"*a T1* \\== *a T2*",
	"*a T1* =\\= *a T2*",
	"*a T1* =@= *a T2*",
	"*a T1* == *a T2*",
	"*a T1* =< *a T2*",
	"*a T1* >= *a T2*",
	"*a T1* = *a T2*",
];